### ISSUE TITLE
Hocam Yardımınıza ihtiyacım var 

### ISSUE THREAD

**Issue by makaay2077** [Mstfakts/Building-Detection-MaskRCNN#2]
Hocam merhabalar.Google Colab'da Yapı algılama modeli oluşturmak istiyorum ama veri boyutu nedeniyle yol alamıyorum bilgisayarıma Mask RCNN kuramıyorum gereksinimleri karşılamıyo ne yapabilirim

**Comment by Mstfakts** [comment]
Merhaba,
SpaceNet datasetini colab'a veya drivea yüklemek çok zor olabilir. Onun yerine kendi bilgisayarınızda çalışmak daha kolay olabilir. Mask-RCNN'i kuramama hakkında daha fazla bilgi verebilir misiniz? Python la ilgili gerekli kurumlarınız var mı? Mask-RCNN'i github dan indirdiniz mi?

**Comment by makaay2077** [comment]
> Merhaba,
> SpaceNet datasetini colab'a veya drivea yüklemek çok zor olabilir. Onun yerine kendi bilgisayarınızda çalışmak daha kolay olabilir. Mask-RCNN'i kuramama hakkında daha fazla bilgi verebilir misiniz? Python la ilgili gerekli kurumlarınız var mı? Mask-RCNN'i github dan indirdiniz mi?

Bunu baya araştırdım Bilgisayara Mask RCNN kurabilmek için bilgisayar GPU destekli ve  NVDİA ekran kartına sahip olmalı (CUDA ).Maalesef eldeki bilgisayarı bunları karşılamıyor AMD ekran kartı ve GPU yok.Google Colab üzerinden çalışıyorum video üzerine mask rcnn çalıştım standart coco dataset üzerinden iyi de oldu ama 22 sn lik videoda nesne algılama toplam 6 saat sürdü.Harita Mühendisiyim ve Harita üzerinde derin öğrenme uygulamaları geliştirmek istiyorum ama veri setleri çok büyük yüklenmiyor driver,colab'a.Pek bir çıkış yolu bulamıyorum.

**Comment by Mstfakts** [comment]
Ben denemedim ama madem donanım sıkıntınız var o zaman Amazon AWS ile deneyebilir misiniz? Hem SpaceNet veriseti de Amazon S3'te, belki orada Colab'dan daha rahat çalışabilirsiniz.
